# Site settings
title: Snail
email: coderz@icloud.com
description: > #test demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://1dong.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


timezone: China/beijing

# Build settings
markdown: kramdown

